[package]
name = "randy"
version = "0.1.0"
authors = ["Benjamin Pannell <bpannell@microsoft.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.6.5"
sentry = "0.15.1"
sentry-actix = "0.15.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
state = "0.4.1"
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }