[package]
name = "randy"
version = "0.1.0"
authors = ["Benjamin Pannell <bpannell@microsoft.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = { version = "0.4.0", features = ["json", "uuid"] }
rocket_cors = "0.4.0"
sentry_rocket = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }
rand = "0.6.5"
sentry = "0.12.0"