[package]
name = "rex"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

[features]
default = []

table_storage = []

[dependencies]
actix = "0.10"
actix-cors = "0.5"
actix-http = "2"
actix-rt = "1"
actix-service = "1"
actix-web = "3"
actix-web-httpauth = "0.5"
async-trait = "0.1.42"
azure_sdk_core = "0.43.7"
azure_sdk_storage_core = "0.44.4"
azure_sdk_storage_table = "0.41.3"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.8"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
md5 = "0.7"
openidconnect = { version = "1.0" }
opentelemetry = { version = "0.12", features = ["tokio"] }
opentelemetry-application-insights = { version = "0.11", features = ["reqwest-client"] }
percent-encoding = "2.1"
rand = "0.8"
reqwest = { version = "0.11" }
sentry = { version = "0.22", features = ["log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-futures = { version = "0.2.4", features = ["futures-03"] }
tracing-opentelemetry = "0.11"
tracing-subscriber = "0.2"
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }