[package]
name = "rex"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

[features]
default = []
table_storage = []

[dependencies]
actix = "0.13"
actix-http = "3.0.0-beta.9"
actix-rt = "2.7"
actix-service = "2.0.2"
actix-web = "4.0.0-beta.8"
async-trait = "0.1.57"
azure_core = { git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_storage = { git = "https://github.com/Azure/azure-sdk-for-rust", features = ["table"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
libhoney-rust = "0.1.3"
log = "0.4"
md5 = "0.7"
openidconnect = { version = "2.3", default_features = false, features = ["curl"] }
opentelemetry = { version = "0.16", features = ["tokio", "rt-tokio"] }
opentelemetry-application-insights = { version = "0.18", features = ["reqwest-client"] }
percent-encoding = "2.1"
rand = "0.8"
reqwest = { version = "0.11" }
sentry = { version = "0.27", features = ["log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.4.0-beta.11"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-honeycomb = "0.4"
tracing-opentelemetry = "0.15"
tracing-subscriber = "0.2"
uuid = { version = "1.1", features = ["serde", "v4"] }