[package]
name = "rex"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

[features]
default = []

table_storage = []

[dependencies]
actix = "0.10"
actix-cors = "0.5"
actix-http = "2.0"
actix-rt = "1.1"
actix-service = "1.0"
actix-web = "3.1"
actix-web-httpauth = "0.5"
actix-web-prom = "0.5"
async-trait = "0.1.41"
azure_sdk_core = "0.43.7"
azure_sdk_storage_core = "0.44.4"
azure_sdk_storage_table = "0.41.3"
biscuit = "0.3"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.7"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
md5 = "0.7"
oidc = "0.3"
percent-encoding = "2.1"
prometheus = "0.10"
rand = "0.7"
reqwest = "0.9"
sentry = { version = "0.20", features = ["log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }