[package]
name = "rex"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-cors = "0.2"
futures = "0.3"
http = "0.2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.6.5"
sentry = "0.17.0"
sentry-actix = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
state = "0.4.1"
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }