[package]
name = "rex"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

[features]
default = []
table_storage = []

[dependencies]
actix = "0.13"
actix-http = "3.2"
actix-rt = "2.7"
actix-service = "2.0.2"
actix-web = "4.2"
async-trait = "0.1.58"
azure_core = "0.8"
azure_data_tables = "0.9"
azure_storage = "0.9"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
md5 = "0.7"
openidconnect = { version = "2.4", default_features = false, features = ["curl"] }
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11", features = ["tls-roots"] }
percent-encoding = "2.2"
rand = "0.8"
reqwest = { version = "0.11" }
sentry = { version = "0.29", features = ["log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.21", features = ["full"] }
tonic = { version = "0.8.3", features = ["tls-roots"] }
tracing = { git="https://github.com/SierraSoftworks/tracing.git" , features = ["log"] }
tracing-actix-web = "0.7.1"
tracing-attributes = { git="https://github.com/SierraSoftworks/tracing.git" }
tracing-futures = { git="https://github.com/SierraSoftworks/tracing.git" , features = ["futures-03"] }
tracing-opentelemetry = { git="https://github.com/SierraSoftworks/tracing.git" }
tracing-subscriber = { git="https://github.com/SierraSoftworks/tracing.git" , features = ["tracing-log"] }
uuid = { version = "1.2", features = ["serde", "v4"] }