---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rex-server
  labels:
    app.kubernetes.io/name: rex
    app.kubernetes.io/instance: rex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rex
      app.kubernetes.io/instance: rex-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rex
        app.kubernetes.io/instance: rex-server
        aadpodidbinding: rex
    spec:
      containers:
        - name: server
          image: sierrasoftworks/rex:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 50Mi
          env:
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TABLE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: connection-string
                  name: rex-secrets
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /api/v1/health
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              port: http
              path: /api/v1/health
            initialDelaySeconds: 30
            periodSeconds: 1