name: Sync API Spec to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: './api/oas3.yaml'
           
          # OPTIONAL CONFIG, use if necessary
          # api-version: 'v1.0.0'
